// In accordance with RFC5102 Section 3.1
var dataTypes = {
  "unsigned8"            : { },
  "unsigned16"           : { },
  "unsigned32"           : { },
  "unsigned64"           : { },
  "signed8"              : { },
  "signed16"             : { },
  "signed32"             : { },
  "signed64"             : { },
  "float32"              : { },
  "float64"              : { },
  "boolean"              : { },
  "macAddress"           : { "key" : "%0-%1-%2-%3-%4-%5"},
  "octetArray"           : { },
  "string"               : { },
  "dateTimeSeconds"      : { },
  "dateTimeMilliseconds" : { },
  "dateTimeMicroseconds" : { },
  "dateTimeNanoseconds"  : { },
  "ipv4Address"          : { "key" : "%0.%1.%2.%3"},
  "ipv6Address"          : { "key" : "%0:%1:%2:%3:%4:%5:%6:%7"}
}

var fieldTypes = {
  1 : { "name" : "octetDeltaCount", "type" : "unsigned64" },
  2 : { "name" : "packetDeltaCount", "type" : "unsigned64" },
  3 : { "name" : "RESERVED" },
  4 : { "name" : "protocolIdentifier", "type" : "unsigned8" },
  5 : { "name" : "ipClassOfService", "type" : "unsigned8" },
  6 : { "name" : "tcpControlBits", "type" : "unsigned8" },
  7 : { "name" : "sourceTransportPort", "type" : "unsigned16" },
  8 : { "name" : "sourceIPv4Address", "type" : "ipv4Address" },
  9 : { "name" : "sourceIPv4PrefixLength", "type" : "unsigned8" },
  10 : { "name" : "ingressInterface", "type" : "unsigned32" },
  11 : { "name" : "destinationTransportPort", "type" : "unsigned16" },
  12 : { "name" : "destinationIPv4Address", "type" : "ipv4Address" },
  13 : { "name" : "destinationIPv4PrefixLength", "type" : "unsigned8" },
  14 : { "name" : "egressInterface", "type" : "unsigned32" },
  15 : { "name" : "ipNextHopIPv4Address", "type" : "ipv4Address" },
  16 : { "name" : "bgpSourceAsNumber", "type" : "unsigned32" },
  17 : { "name" : "bgpDestinationAsNumber", "type" : "unsigned32" },
  18 : { "name" : "bgpNexthopIPv4Address", "type" : "ipv4Address" },
  19 : { "name" : "postMCastPacketDeltaCount", "type" : "unsigned64" },
  20 : { "name" : "postMCastOctetDeltaCount", "type" : "unsigned64" },
  21 : { "name" : "flowEndSysUpTime", "type" : "unsigned32" },
  22 : { "name" : "flowStartSysUpTime", "type" : "unsigned32" },
  23 : { "name" : "postOctetDeltaCount", "type" : "unsigned64" },
  24 : { "name" : "postPacketDeltaCount", "type" : "unsigned64" },
  25 : { "name" : "minimumIpTotalLength", "type" : "unsigned64" },
  26 : { "name" : "maximumIpTotalLength", "type" : "unsigned64" },
  27 : { "name" : "sourceIPv6Address", "type" : "ipv6Address" },
  28 : { "name" : "destinationIPv6Address", "type" : "ipv6Address" },
  29 : { "name" : "sourceIPv6PrefixLength", "type" : "unsigned8" },
  30 : { "name" : "destinationIPv6PrefixLength", "type" : "unsigned8" },
  31 : { "name" : "flowLabelIPv6", "type" : "unsigned32" },
  32 : { "name" : "icmpTypeCodeIPv4", "type" : "unsigned16" },
  33 : { "name" : "igmpType", "type" : "unsigned8" },
  34 : { "name" : "RESERVED" },
  35 : { "name" : "RESERVED" },
  36 : { "name" : "flowActiveTimeout", "type" : "unsigned16" },
  37 : { "name" : "flowIdleTimeout", "type" : "unsigned16" },
  38 : { "name" : "RESERVED" },
  39 : { "name" : "RESERVED" },
  40 : { "name" : "exportedOctetTotalCount", "type" : "unsigned64" },
  41 : { "name" : "exportedMessageTotalCount", "type" : "unsigned64" },
  42 : { "name" : "exportedFlowRecordTotalCount", "type" : "unsigned64" },
  43 : { "name" : "RESERVED" },
  44 : { "name" : "sourceIPv4Prefix", "type" : "ipv4Address" },
  45 : { "name" : "destinationIPv4Prefix", "type" : "ipv4Address" },
  46 : { "name" : "mplsTopLabelType", "type" : "unsigned8" },
  47 : { "name" : "mplsTopLabelIPv4Address", "type" : "ipv4Address" },
  48 : { "name" : "RESERVED" },
  49 : { "name" : "RESERVED" },
  50 : { "name" : "RESERVED" },
  51 : { "name" : "RESERVED" },
  52 : { "name" : "minimumTTL", "type" : "unsigned8" },
  53 : { "name" : "maximumTTL", "type" : "unsigned8" },
  54 : { "name" : "fragmentIdentification", "type" : "unsigned32" },
  55 : { "name" : "postIpClassOfService", "type" : "unsigned8" },
  56 : { "name" : "sourceMacAddress", "type" : "macAddress" },
  57 : { "name" : "postDestinationMacAddress", "type" : "macAddress" },
  58 : { "name" : "vlanId", "type" : "unsigned16" },
  59 : { "name" : "postVlanId", "type" : "unsigned16" },
  60 : { "name" : "ipVersion", "type" : "unsigned8" },
  61 : { "name" : "flowDirection", "type" : "unsigned8" },
  62 : { "name" : "ipNextHopIPv6Address", "type" : "ipv6Address" },
  63 : { "name" : "bgpNexthopIPv6Address", "type" : "ipv6Address" },
  64 : { "name" : "ipv6ExtensionHeaders", "type" : "unsigned64" },
  65 : { "name" : "RESERVED" },
  66 : { "name" : "RESERVED" },
  67 : { "name" : "RESERVED" },
  68 : { "name" : "RESERVED" },
  69 : { "name" : "RESERVED" },
  70 : { "name" : "mplsTopLabelStackSection", "type" : "octetArray" },
  71 : { "name" : "mplsLabelStackSection2", "type" : "octetArray" },
  72 : { "name" : "mplsLabelStackSection3", "type" : "octetArray" },
  73 : { "name" : "mplsLabelStackSection4", "type" : "octetArray" },
  74 : { "name" : "mplsLabelStackSection5", "type" : "octetArray" },
  75 : { "name" : "mplsLabelStackSection6", "type" : "octetArray" },
  76 : { "name" : "mplsLabelStackSection7", "type" : "octetArray" },
  77 : { "name" : "mplsLabelStackSection8", "type" : "octetArray" },
  78 : { "name" : "mplsLabelStackSection9", "type" : "octetArray" },
  79 : { "name" : "mplsLabelStackSection10", "type" : "octetArray" },
  80 : { "name" : "destinationMacAddress", "type" : "macAddress" },
  81 : { "name" : "postSourceMacAddress", "type" : "macAddress" },
  82 : { "name" : "RESERVED" },
  83 : { "name" : "RESERVED" },
  84 : { "name" : "RESERVED" },
  85 : { "name" : "octetTotalCount", "type" : "unsigned64" },
  86 : { "name" : "packetTotalCount", "type" : "unsigned64" },
  87 : { "name" : "RESERVED" },
  88 : { "name" : "fragmentOffset", "type" : "unsigned16" },
  89 : { "name" : "RESERVED" },
  90 : { "name" : "mplsVpnRouteDistinguisher", "type" : "octetArray" },
  91 : { "name" : "RESERVED" },
  92 : { "name" : "RESERVED" },
  93 : { "name" : "RESERVED" },
  94 : { "name" : "RESERVED" },
  95 : { "name" : "RESERVED" },
  96 : { "name" : "RESERVED" },
  97 : { "name" : "RESERVED" },
  98 : { "name" : "RESERVED" },
  99 : { "name" : "RESERVED" },
  100 : { "name" : "RESERVED" },
  101 : { "name" : "RESERVED" },
  102 : { "name" : "RESERVED" },
  103 : { "name" : "RESERVED" },
  104 : { "name" : "RESERVED" },
  105 : { "name" : "RESERVED" },
  106 : { "name" : "RESERVED" },
  107 : { "name" : "RESERVED" },
  108 : { "name" : "RESERVED" },
  109 : { "name" : "RESERVED" },
  110 : { "name" : "RESERVED" },
  111 : { "name" : "RESERVED" },
  112 : { "name" : "RESERVED" },
  113 : { "name" : "RESERVED" },
  114 : { "name" : "RESERVED" },
  115 : { "name" : "RESERVED" },
  116 : { "name" : "RESERVED" },
  117 : { "name" : "RESERVED" },
  118 : { "name" : "RESERVED" },
  119 : { "name" : "RESERVED" },
  120 : { "name" : "RESERVED" },
  121 : { "name" : "RESERVED" },
  122 : { "name" : "RESERVED" },
  123 : { "name" : "RESERVED" },
  124 : { "name" : "RESERVED" },
  125 : { "name" : "RESERVED" },
  126 : { "name" : "RESERVED" },
  127 : { "name" : "RESERVED" },
  128 : { "name" : "bgpNextAdjacentAsNumber", "type" : "unsigned32" },
  129 : { "name" : "bgpPrevAdjacentAsNumber", "type" : "unsigned32" },
  130 : { "name" : "exporterIPv4Address", "type" : "ipv4Address" },
  131 : { "name" : "exporterIPv6Address", "type" : "ipv6Address" },
  132 : { "name" : "droppedOctetDeltaCount", "type" : "unsigned64" },
  133 : { "name" : "droppedPacketDeltaCount", "type" : "unsigned64" },
  134 : { "name" : "droppedOctetTotalCount", "type" : "unsigned64" },
  135 : { "name" : "droppedPacketTotalCount", "type" : "unsigned64" },
  136 : { "name" : "flowEndReason", "type" : "unsigned8" },
  137 : { "name" : "commonPropertiesId", "type" : "unsigned64" },
  138 : { "name" : "observationPointId", "type" : "unsigned32" },
  139 : { "name" : "icmpTypeCodeIPv6", "type" : "unsigned16" },
  140 : { "name" : "mplsTopLabelIPv6Address", "type" : "ipv6Address" },
  141 : { "name" : "lineCardId", "type" : "unsigned32" },
  142 : { "name" : "portId", "type" : "unsigned32" },
  143 : { "name" : "meteringProcessId", "type" : "unsigned32" },
  144 : { "name" : "exportingProcessId", "type" : "unsigned32" },
  145 : { "name" : "templateId", "type" : "unsigned16" },
  146 : { "name" : "wlanChannelId", "type" : "unsigned8" },
  147 : { "name" : "wlanSSID", "type" : "string" },
  148 : { "name" : "flowId", "type" : "unsigned64" },
  149 : { "name" : "observationDomainId", "type" : "unsigned32" },
  150 : { "name" : "flowStartSeconds", "type" : "dateTimeSeconds" },
  151 : { "name" : "flowEndSeconds", "type" : "dateTimeSeconds" },
  152 : { "name" : "flowStartMilliseconds", "type" : "dateTimeMilliseconds" },
  153 : { "name" : "flowEndMilliseconds", "type" : "dateTimeMilliseconds" },
  154 : { "name" : "flowStartMicroseconds", "type" : "dateTimeMicroseconds" },
  155 : { "name" : "flowEndMicroseconds", "type" : "dateTimeMicroseconds" },
  156 : { "name" : "flowStartNanoseconds", "type" : "dateTimeNanoseconds" },
  157 : { "name" : "flowEndNanoseconds", "type" : "dateTimeNanoseconds" },
  158 : { "name" : "flowStartDeltaMicroseconds", "type" : "unsigned32" },
  159 : { "name" : "flowEndDeltaMicroseconds", "type" : "unsigned32" },
  160 : { "name" : "systemInitTimeMilliseconds", "type" : "dateTimeMilliseconds" },
  161 : { "name" : "flowDurationMilliseconds", "type" : "unsigned32" },
  162 : { "name" : "flowDurationMicroseconds", "type" : "unsigned32" },
  163 : { "name" : "observedFlowTotalCount", "type" : "unsigned64" },
  164 : { "name" : "ignoredPacketTotalCount", "type" : "unsigned64" },
  165 : { "name" : "ignoredOctetTotalCount", "type" : "unsigned64" },
  166 : { "name" : "notSentFlowTotalCount", "type" : "unsigned64" },
  167 : { "name" : "notSentPacketTotalCount", "type" : "unsigned64" },
  168 : { "name" : "notSentOctetTotalCount", "type" : "unsigned64" },
  169 : { "name" : "destinationIPv6Prefix", "type" : "ipv6Address" },
  170 : { "name" : "sourceIPv6Prefix", "type" : "ipv6Address" },
  171 : { "name" : "postOctetTotalCount", "type" : "unsigned64" },
  172 : { "name" : "postPacketTotalCount", "type" : "unsigned64" },
  173 : { "name" : "flowKeyIndicator", "type" : "unsigned64" },
  174 : { "name" : "postMCastPacketTotalCount", "type" : "unsigned64" },
  175 : { "name" : "postMCastOctetTotalCount", "type" : "unsigned64" },
  176 : { "name" : "icmpTypeIPv4", "type" : "unsigned8" },
  177 : { "name" : "icmpCodeIPv4", "type" : "unsigned8" },
  178 : { "name" : "icmpTypeIPv6", "type" : "unsigned8" },
  179 : { "name" : "icmpCodeIPv6", "type" : "unsigned8" },
  180 : { "name" : "udpSourcePort", "type" : "unsigned16" },
  181 : { "name" : "udpDestinationPort", "type" : "unsigned16" },
  182 : { "name" : "tcpSourcePort", "type" : "unsigned16" },
  183 : { "name" : "tcpDestinationPort", "type" : "unsigned16" },
  184 : { "name" : "tcpSequenceNumber", "type" : "unsigned32" },
  185 : { "name" : "tcpAcknowledgementNumber", "type" : "unsigned32" },
  186 : { "name" : "tcpWindowSize", "type" : "unsigned32" },
  187 : { "name" : "tcpUrgentPointer", "type" : "unsigned16" },
  188 : { "name" : "tcpHeaderLength", "type" : "unsigned8" },
  189 : { "name" : "ipHeaderLength", "type" : "unsigned8" },
  190 : { "name" : "totalLengthIPv4", "type" : "unsigned16" },
  191 : { "name" : "payloadLengthIPv6", "type" : "unsigned16" },
  192 : { "name" : "ipTTL", "type" : "unsigned8" },
  193 : { "name" : "nextHeaderIPv6", "type" : "unsigned8" },
  194 : { "name" : "mplsPayloadLength", "type" : "unsigned32" },
  195 : { "name" : "ipDiffServCodePoint", "type" : "unsigned8" },
  196 : { "name" : "ipPrecedence", "type" : "unsigned8" },
  197 : { "name" : "fragmentFlags", "type" : "unsigned8" },
  198 : { "name" : "octetDeltaSumOfSquares", "type" : "unsigned64" },
  199 : { "name" : "octetTotalSumOfSquares", "type" : "unsigned64" },
  200 : { "name" : "mplsTopLabelTTL", "type" : "unsigned8" },
  201 : { "name" : "mplsLabelStackLength", "type" : "unsigned32" },
  202 : { "name" : "mplsLabelStackDepth", "type" : "unsigned32" },
  203 : { "name" : "mplsTopLabelExp", "type" : "unsigned8" },
  204 : { "name" : "ipPayloadLength", "type" : "unsigned32" },
  205 : { "name" : "udpMessageLength", "type" : "unsigned16" },
  206 : { "name" : "isMulticast", "type" : "unsigned8" },
  207 : { "name" : "ipv4IHL", "type" : "unsigned8" },
  208 : { "name" : "ipv4Options", "type" : "unsigned32" },
  209 : { "name" : "tcpOptions", "type" : "unsigned64" },
  210 : { "name" : "paddingOctets", "type" : "octetArray" },
  211 : { "name" : "collectorIPv4Address", "type" : "ipv4Address" },
  212 : { "name" : "collectorIPv6Address", "type" : "ipv6Address" },
  213 : { "name" : "exportInterface", "type" : "unsigned32" },
  214 : { "name" : "exportProtocolVersion", "type" : "unsigned8" },
  215 : { "name" : "exportTransportProtocol", "type" : "unsigned8" },
  216 : { "name" : "collectorTransportPort", "type" : "unsigned16" },
  217 : { "name" : "exporterTransportPort", "type" : "unsigned16" },
  218 : { "name" : "tcpSynTotalCount", "type" : "unsigned64" },
  219 : { "name" : "tcpFinTotalCount", "type" : "unsigned64" },
  220 : { "name" : "tcpRstTotalCount", "type" : "unsigned64" },
  221 : { "name" : "tcpPshTotalCount", "type" : "unsigned64" },
  222 : { "name" : "tcpAckTotalCount", "type" : "unsigned64" },
  223 : { "name" : "tcpUrgTotalCount", "type" : "unsigned64" },
  224 : { "name" : "ipTotalLength", "type" : "unsigned64" },
  237 : { "name" : "postMplsTopLabelExp", "type" : "unsigned8" },
  238 : { "name" : "tcpWindowScale", "type" : "unsigned16" }
}

exports.dataTypes = dataTypes;
exports.fieldTypes = fieldTypes;
